using System;

namespace OneCSharp.DDL.Attributes
{
    public abstract class Persistent { } // marker class for database entities to use in DSL syntax tree as a type constraint
    public abstract class ReferenceObject : Persistent
    {
        [Field(Name = "_IDRRef", TypeName = "binary", Length = 16, IsPrimaryKey = true)] public Guid Ссылка { get; set; }
    }

    public enum FieldPurpose
    {
        /// <summary>Value of the property (default).</summary>
        Value,
        /// <summary>Helps to locate fields having [boolean, string, number, binary, datetime, object] types</summary>
        Discriminator,
        /// <summary>Boolean value.</summary>
        Boolean,
        /// <summary>String value.</summary>
        String,
        /// <summary>Numeric value.</summary>
        Numeric,
        /// <summary>Binary value (bytes array).</summary>
        Binary,
        /// <summary>Date and time value.</summary>
        DateTime,
        /// <summary>Reference type primary key value.</summary>
        Object,
        /// <summary>Type code of the reference type (class discriminator).</summary>
        TypeCode,
        /// <summary>Record's version (timestamp|rowversion).</summary>
        Version,
        /// <summary>Ordinal key value for ordered sets of records.</summary>
        Ordinal
    }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)] public sealed class EntityAttribute : Attribute
    {
        public Guid UUID { get; set; }
        public int TypeCode { get; set; }
        public string TableName { get; set; }
    }
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = false)] public sealed class FieldAttribute : Attribute
    {
        public string Name { get; set; }
        public string TypeName { get; set; }
        public int Length { get; set; }
        public byte Precision { get; set; }
        public int Scale { get; set; }
        public bool IsNullable { get; set; }
        public bool IsPrimaryKey { get; set; }
        public int KeyOrdinal { get; set; }
        public bool IsAutoGenerated { get; set; }
        public FieldPurpose Purpose { get; set; }
    }
}